### ISSUE TITLE
Solitaire games do not account for visibility state of cards

### ISSUE THREAD

**Issue by deoxys314** [rktjmp/playtime.nvim#3]
Once in a while, you can manipulate an unexposed card on a stack, if by chance it happens to be the correct suit and value that you would be able to do so anyway. In the attached screenshot, you can see an instance of this in the completed stacks at the top right - I had a large stack which was led by a Queen. I added a few cards down to an Ace on the bottom, thinking I would have to find a King later. However, the stack completed itself, because by chance the Queen had been on top of an unexposed King. Interestingly, the card "object" remembers it's state - it's still rendered as a card back in the top right.

![image](https://github.com/user-attachments/assets/5edcf73e-21d2-41e4-9c51-fdcce550c5af)

I think this is cool and fun, personally. It rarely matters in any major way, as one doesn't try to manipulate the unexposed portions of stacks. In this case, it did have a large affect on the game state, and no matter your view, this is a departure from the physical-card version of the game, which I assume is what we're trying to emulate here.

**Comment by rktjmp** [comment]
Thanks for the report! Not intentional but should be fixed now.
