### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by Bossach** [rktjmp/playtime.nvim#5]
Hello! I faced some error:
```
Error executing Lua callback: ...share/nvim/lazy/playtime.nvim/lua/playtime/highlight.lua:43: invalid key: create
stack traceback:
        [C]: in function 'nvim_get_hl'
        ...share/nvim/lazy/playtime.nvim/lua/playtime/highlight.lua:43: in function 'hl'
        ...share/nvim/lazy/playtime.nvim/lua/playtime/highlight.lua:53: in function 'define-highlights'
        ...hare/nvim/lazy/playtime.nvim/lua/playtime/app/window.lua:114: in function 'open'
        ...im/lazy/playtime.nvim/lua/playtime/app/patience/init.lua:41: in function 'start'
        ...aytime.nvim/lua/playtime/game/shenzhen-solitaire/app.lua:114: in function <...aytime.nvim/lua/playtime/game/shenzhen-solitaire/app.lua:113>
:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1723681758

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue

```

In my `:help nvim_get_hl` there is no 'create' option at all. Simply deleting it from `highlight.lua:43` makes it technically work, but I left without colors and probably icons. How to fix that? Thanks.

![image](https://github.com/user-attachments/assets/2ed0adde-1979-4234-9218-63f89001e86a)

**Comment by rktjmp** [comment]
Can you check the latest on the main branch? You should not see an error and you should also see highlights.

**Comment by Bossach** [comment]
Error gone. But unfortunately still all-white for some reason. (Icons are shown indeed, but seems particular "shenzhen solitare" has no ones, that's probably not an issue)

**Comment by rktjmp** [comment]
What colorscheme are you using? It tries to pick colors from the current colorscheme, perhaps they're not defined

https://github.com/rktjmp/playtime.nvim/blob/c59f03d4b871fe9f7cb0a9e7f242a84237600996/fnl/playtime/highlight.fnl#L68-L82

You can manually define these groups before starting Playtime and it should pick them up. You should define them inside a `ColorScheme` autocmd so they're correctly set if you change your colorscheme.

eg something like (untested, check docs):

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
    callback = function()
        vim.api.nvim_set_hl(0, "PlaytimeGreen", { fg = "green" })
    end,
})
```

Make sure you create the autocmd before setting your normal colorscheme, or set them in addition to creating the autocmd.

**Comment by rktjmp** [comment]
You can manually define these groups before starting playtime and it should pick them up

**Comment by Bossach** [comment]
I use default 'desert' colorscheme. Switched to another defaults same result (colors are different, but still only two of them). Comments, warnings and so on in code are colored. 

This code
```
vim.api.nvim_create_autocmd("ColorScheme", {
    callback = function()
        vim.api.nvim_set_hl(0, "PlaytimeGreen", { fg = "green" })
    end,
})
```
seems no effect (I've put it in init.vim), still all-white (although I don't yet understand what it does, as don't understand colors in nvim at all)

**Comment by rktjmp** [comment]
Ah, the code I gave you goes in `init.lua`, not `init.vim`, you should not need it though if below is the issue.

I believe I have tracked it down, probably you do not have `termguicolors` enabled which limits the color palette used in nvim (not just playtime, but all of nvim).

If you press `:` to open the command line and enter `set termguicolors?`, does it say `notermguicolors`?


![image](https://github.com/user-attachments/assets/d56bfb54-11ef-407e-90a9-c3bd15afa339)

![image](https://github.com/user-attachments/assets/83d047f6-c17d-4826-8dc0-d3d33671cc7f)

Try running `:set termguicolors`

![image](https://github.com/user-attachments/assets/90708595-9bcb-4d9f-a189-51ebb57353d5)

I believe its fine to enable `termguicolors` all the time these days (ie put it in your init.vim), as all modern terminal emulators can handle 24 bit colors, though if you use tmux or screen you might need to ensure you're passing the correct `xterm-256collor` flags in its config too.

**Comment by Bossach** [comment]
Yes, that was exactly `termguicolors`. Thank you for help!
